CREATE DATABASE `BAITAPTONGHOP`;
USE `BAITAPTONGHOP`;
CREATE TABLE `BOOK`(
	`Book_Id` CHAR(5) PRIMARY KEY,
    `Book_Name` VARCHAR(200) NOT NULL,
    `Book_Quanity` INT CHECK (`Book_Quanity` >= 0),
    `Book_Rent` DECIMAL(10,2) DEFAULT 5000
);
ALTER TABLE `BOOK` 
	ADD COLUMN `Book_Date` DATE;

CREATE TABLE `BORROW_BOOKS`(
	`Borrow_Id` INT PRIMARY KEY AUTO_INCREMENT,
    `Book_Id` CHAR(5),
    FOREIGN KEY (`Book_Id`) REFERENCES `BOOK` (`Book_Id`),
    `Day_Rent` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
